Rails.application.config.assets.precompile += %w( dashboard.css ) 
Rails.application.config.assets.precompile += %w( home.css )
Rails.application.config.assets.precompile += %w( header.css )
Rails.application.config.assets.precompile += %w( profile.css )
Rails.application.config.assets.precompile += %w( home.js )
Rails.application.config.assets.precompile += %w( dashboard.js )
Rails.application.config.assets.precompile += %w( profile.js )
